lando/lando#2679: Use DROP/CREATE strategy for MySQL DB reset
lando/cli pull request #59
Opened 2021-11-02 22:24 UTC by xurizaemon

2022-02-09 23:01 UTC, reynoldsalec requested changes
Change is non-working; see comment and the test results. Guessing it's something about that DB command based on the errors.

2022-02-09 23:01 UTC, reynoldsalec commented on plugins/lando-services/scripts/sql-import.sh
> +    $SQLSTART -e "DROP DATABASE IF EXISTS ${DATABASE}"
Something about this line is failing (see the test results for the PR or try using the [db-export example](https://github.com/lando/cli/blob/main/examples/sql-export/README.md) and running the `lando db-import test.sql` on it).

2022-10-10 17:56 UTC, xurizaemon commented
30155c8 does not address the requested changes above, just rebasing to pick up current main.

2022-10-10 19:42 UTC, xurizaemon commented
I can now see https://github.com/lando/cli/actions/runs/3221353780/jobs/5269616590 is the failing job

2023-07-21 19:23 UTC, xurizaemon commented
Closing PR in favour of https://github.com/lando/core-next/pull/40

2023-07-21 19:23 UTC, closed without merging